import type { GameAction, SidebarMode } from "@/lib/types";

const baseActionDefinitions: Record<SidebarMode, GameAction[]> = {
  build: [
    {
      id: "post-content",
      title: "Post Content",
      description: "Feed the machine with something polished, strategic, and slightly insufferable.",
      source: "base",
      group: "build",
      icon: "Clapperboard",
      cost: { burnout: 10 },
      upside: "Reliable audience growth",
      risk: "Audience may notice the hustle leaking through the caption.",
      statEffects: { followers: 3_100, engagement: 2.2, trust: -1, exposureRisk: 3, burnout: 10 },
      boardTile: "Content Studio",
    },
    {
      id: "improve-product",
      title: "Improve Product",
      description: "Make the offer better so the persona can survive one more round of scrutiny.",
      source: "base",
      group: "build",
      icon: "Wrench",
      cost: { money: -300, burnout: 6 },
      upside: "Boosts trust and credibility",
      risk: "Cash leaves before applause arrives.",
      statEffects: { money: 1_250, trust: 4, credibility: 5, burnout: 6, exposureRisk: -1 },
      boardTile: "Product Lab",
    },
    {
      id: "network",
      title: "Network",
      description: "Borrow status from people with better lanyards, better lighting, or better tables.",
      source: "base",
      group: "build",
      icon: "Handshake",
      cost: { money: -200, burnout: 5 },
      upside: "Builds clout and trust",
      risk: "Can feel desperate if overdone.",
      statEffects: { followers: 1_250, trust: 4, credibility: 3, burnout: 5, money: 250 },
      boardTile: "Community Hub",
    },
    {
      id: "monetize",
      title: "Monetize",
      description: "Convert attention into a product, drop, course, affiliate code, or tasteful invoice.",
      source: "base",
      group: "build",
      icon: "WalletCards",
      cost: { trust: -5, burnout: 8 },
      upside: "Highest cash upside",
      risk: "Trust takes the hit if it feels greedy.",
      statEffects: { money: 3_200, followers: 500, trust: -5, exposureRisk: 4, burnout: 8, credibility: -2 },
      boardTile: "Product Funnel",
    },
    {
      id: "recover",
      title: "Recover",
      description: "Disappear just enough to feel intentional instead of irrelevant.",
      source: "base",
      group: "build",
      icon: "MoonStar",
      cost: {},
      upside: "Reduces burnout and heat",
      risk: "Slight momentum loss",
      statEffects: { followers: -250, engagement: -0.6, trust: 2, exposureRisk: -4, burnout: -18, credibility: 1 },
      boardTile: "Recovery Zone",
    },
  ],
  drama: [
    {
      id: "hot-take",
      title: "Hot Take",
      description: "Quote-post a confident opinion nobody asked for and let the timeline decide.",
      source: "base",
      group: "drama",
      icon: "Flame",
      cost: { burnout: 7 },
      upside: "Fast spikes in engagement",
      risk: "Trust can sag if it feels performative.",
      statEffects: { followers: 2_600, engagement: 4, trust: -4, exposureRisk: 7, burnout: 7 },
      boardTile: "Hot Take Platform",
    },
    {
      id: "call-out-rival",
      title: "Call Out Rival",
      description: "Name the behavior, imply the target, and let everyone fill in the blanks.",
      source: "base",
      group: "drama",
      icon: "Swords",
      cost: { burnout: 8 },
      upside: "Steals a little spotlight",
      risk: "Looks insecure if the swing misses.",
      statEffects: { followers: 2_200, engagement: 3.2, trust: -2, exposureRisk: 8, burnout: 8, credibility: -1 },
      boardTile: "Callout Stage",
    },
    {
      id: "rage-bait",
      title: "Rage Bait",
      description: "Say the thing that makes everyone furious enough to share it for free.",
      source: "base",
      group: "drama",
      icon: "Siren",
      cost: { trust: -7, burnout: 10 },
      upside: "Huge growth burst",
      risk: "Exposure risk rockets upward.",
      statEffects: { followers: 4_100, engagement: 5.5, trust: -7, exposureRisk: 12, burnout: 10, credibility: -3 },
      boardTile: "Drama Zone",
    },
    {
      id: "flex-harder",
      title: "Flex Harder",
      description: "Rent atmosphere, borrow confidence, and let the audience do the extrapolating.",
      source: "base",
      group: "drama",
      icon: "Gem",
      cost: { money: -1_100, burnout: 5 },
      upside: "Builds aspiration",
      risk: "Can look fragile if the luxury feels rented.",
      statEffects: { followers: 1_850, engagement: 2.5, trust: -3, exposureRisk: 5, burnout: 5, credibility: 1 },
      boardTile: "Lifestyle Flex Suite",
    },
    {
      id: "copy-trend",
      title: "Copy Trend",
      description: "Move fast, borrow the format, and pray your audience calls it timely.",
      source: "base",
      group: "drama",
      icon: "CopyPlus",
      cost: { burnout: 6 },
      upside: "Cheap reach",
      risk: "Credibility gets a little thinner.",
      statEffects: { followers: 1_650, engagement: 3.4, credibility: -3, exposureRisk: 2, burnout: 6, money: 150 },
      boardTile: "Trend Reactor",
    },
  ],
};

export function getBaseActions(mode: SidebarMode) {
  return baseActionDefinitions[mode];
}

export function getAllBaseActions() {
  return [...baseActionDefinitions.build, ...baseActionDefinitions.drama];
}

export function getActionById(actionId: string) {
  return getAllBaseActions().find((action) => action.id === actionId) ?? null;
}
